logging:
  mode: offline
  project: Cell-Segmentation
  notes: CellViT-256
  log_comment: CellViT-256-Fold-1
  tags:
  - Fold-1
  - ViT256
  wandb_dir: /home/ravi/sanika/CellViT/logs/PanNuke/WandB
  log_dir:   /home/ravi/sanika/CellViT/logs/PanNuke/Log
  level: Debug
  group: CellViT256
random_seed: 19
gpu: 0
data:
  dataset: PanNuke
  dataset_path: /home/Drivessd2tb/sanika_data/PanNuke/Prepared
  train_folds:
  - 0
  val_folds:
  - 1
  test_folds:
  - 2
  num_nuclei_classes: 6
  num_tissue_classes: 19
model:
  backbone: ViT256
  #backbone: SAM-H
  #pretrained_encoder: /home/Drivessd2tb/sanika_data/models/pretrained_encoders/vit256_small_dino.pth
  #pretrained_encoder: /home/Drivessd2tb/sanika_data/models/pretrained_encoders/sam2_hiera_small.pt
  pretrained_encoder: /home/Drivessd2tb/sanika_data/models/pretrained_encoders/dino_deitsmall16_pretrain_full_checkpoint.pth
  #pretrained_encoder: /home/Drivessd2tb/sanika_data/models/pretrained_encoders/pytorch_model.bin # UNI
  shared_skip_connections: true
loss:
  nuclei_binary_map:
    focaltverskyloss:
      loss_fn: FocalTverskyLoss
      weight: 1
    dice:
      loss_fn: dice_loss
      weight: 1
    #samsloss:
      #loss_fn: SAMSLoss
      #weight: 0.00005
    #bendingloss:
      #loss_fn: BendingLoss
      #weight: 0.00005
    #lossvariance:
      #loss_fn: LossVariance
      #weight: 0.01
  hv_map:
    #mse:
      #loss_fn: mse_loss_maps
      #weight: 2.5
    huber:
      loss_fn: huber_loss_maps
      weight: 2.5
      args:
        delta: 1
    msge:
      loss_fn: msge_loss_maps
      weight: 8
  nuclei_type_map:
    bce:
      loss_fn: xentropy_loss
      weight: 0.5
    lossvariance:
      loss_fn: LossVariance
      weight: 0.5
    dice:
      loss_fn: dice_loss
      weight: 0.2
    mcfocaltverskyloss:
      loss_fn: MCFocalTverskyLoss
      weight: 0.5
      args:
        num_classes: 6
  tissue_types:
    ce:
      loss_fn: CrossEntropyLoss
      weight: 0.1
    #lossvariance:
      #loss_fn: LossVariance
      #weight: 0.01
training:
  drop_rate: 0
  attn_drop_rate: 0.1
  drop_path_rate: 0.1
  batch_size: 16
  epochs: 130
  optimizer: AdamW
  early_stopping_patience: 25 # original: 130
  scheduler:
    scheduler_type: exponential
    hyperparameters:
      gamma: 0.85
  optimizer_hyperparameter:
    betas:
    - 0.85
    - 0.95
    lr: 0.0003
    weight_decay: 0.0001
  unfreeze_epoch: 25
  sampling_gamma: 0.85
  sampling_strategy: cell+tissue
  mixed_precision: true
transformations:
  randomrotate90:
    p: 0.5
  horizontalflip:
    p: 0.5
  verticalflip:
    p: 0.5
  downscale:
    p: 0.15
    scale: 0.9
  blur:
    p: 0.2
    blur_limit: 10
  gaussnoise:
    p: 0.25
    var_limit: 50
  colorjitter:
    p: 0.2
    scale_setting: 0.25
    scale_color: 0.1
  superpixels:
    p: 0.1
  zoomblur:
    p: 0.1
  randomsizedcrop:
    p: 0.1
  elastictransform:
    p: 0.2
  # -------------------------Additional Transforms----------------------
  affine:
    shear: 10
    p: 0.5 
  randombrightnesscontrast:
    brightness_limit: 0.1
    contrast_limit: 0.1
    p: 0.5
  # --------------------------------------------------------------------
  normalize:
    mean:
    - 0.5
    - 0.5
    - 0.5
    std:
    - 0.5
    - 0.5
    - 0.5
eval_checkpoint: latest_checkpoint.pth
run_sweep: false
agent: null
