# dataset paths
wsi_paths: /home/Drivessd2tb/sanika_data/PUMA/Prepared/fold0
output_path: /home/Drivessd2tb/sanika_data/PUMA/Preprocessed/fold0

# basic setups
patch_size: 256
patch_overlap: 25 #6.25
target_mag: 40
processes: 8
overwrite: True
#wsi_extension: tif

# macenko stain normalization
normalize_stains: True

# finding patches
min_intersection_ratio: 0.05
